name: terraform
on:
  pull_request:
  push:
    branches:
      - main
env:
  TERRAFORM_VERSION:                 "1.1.2"
  GOOGLE_PROJECT:                    "${{secrets.TF_VAR_google_project_id}}"
  GOOGLE_APPLICATION_CREDENTIALS:    "google.json"
  TF_VAR_GOOGLE_CREDENTIALS:         "google.json"
  TF_VAR_ORG_NAME:                   "${{secrets.TF_VAR_ORG_NAME}}"
  TF_VAR_google_project_id:          "${{secrets.TF_VAR_google_project_id}}"
  TF_VAR_google_gloud_zone:          "${{secrets.TF_VAR_google_gloud_zone}}"
  TF_VAR_argocd_password:            "${{secrets.TF_VAR_argocd_password}}"
  TF_VAR_domain:                     "${{secrets.TF_VAR_domain}}"
  TF_VAR_subdomain:                  "${{secrets.TF_VAR_subdomain}}"
jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: check that configuration exists
        id: configuration
        run: |
          echo ::set-output name=present::false
          if ls *.tf &>/dev/null; then
            echo "Configuration present"
            echo ::set-output name=present::true
          else
            echo "No configuration for terraform yet"
          fi
      - name: get terraform
        if: ${{steps.configuration.outputs.present == 'true'}}
        run: |
          curl -L -s https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip -o terraform.zip
          unzip -d bin terraform.zip
      - name: add workspace/bin to path
        if: ${{steps.configuration.outputs.present == 'true'}}
        run: echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
      - name: save google creds json
        if: ${{steps.configuration.outputs.present == 'true'}}
        run:  echo '${{secrets.GOOGLE_CREDENTIALS}}' | dd of=google.json
      - name: init
        if: ${{steps.configuration.outputs.present == 'true'}}
        run: terraform init
        env:
          TF_VAR_GITHUB_TOKEN: ${{secrets.TF_VAR_GITHUB_TOKEN}}
      - name: validate
        if: ${{steps.configuration.outputs.present == 'true'}}
        run:  terraform validate
      - name: check fmt
        if: ${{steps.configuration.outputs.present == 'true'}}
        run:  terraform fmt -check
      - name: plan
        if: ${{steps.configuration.outputs.present == 'true'}}
        id: plan
        run: |
          echo ::set-output name=plan_has_changes::false
          if terraform plan -detailed-exitcode; then
             echo "No changes detected"
          else
             export planExitCode=$?
             if [ ${planExitCode} -eq 2 ]; then
                echo ::set-output name=plan_has_changes::true
                echo "Plan succeeded and there are some changes"
                exit 0
             fi
          fi
          exit ${planExitCode}
        env:
          TF_VAR_GITHUB_TOKEN: ${{secrets.TF_VAR_GITHUB_TOKEN}}
      - name: apply -refresh-only
        if: ${{github.ref == 'refs/heads/main' && steps.plan.outputs.plan_has_changes == 'false' && steps.configuration.outputs.present == 'true'}}
        run: terraform apply -refresh-only -auto-approve
        env:
          TF_VAR_GITHUB_TOKEN: ${{secrets.TF_VAR_GITHUB_TOKEN}}
      - name: apply
        if: ${{github.ref == 'refs/heads/main' && steps.plan.outputs.plan_has_changes == 'true' && steps.configuration.outputs.present == 'true'}}
        run: terraform apply -auto-approve
        env:
          TF_VAR_GITHUB_TOKEN: ${{secrets.TF_VAR_GITHUB_TOKEN}}
      - name: output
        run: |
          terraform output -json >> output.json
          echo "gke loadbalancer ip addresses:"
          cat output.json | jq -r 'to_entries[] | select(.key | contains("gke")) | .key+"\t"+.value.value[]'
          echo "nameservers:"
          cat output.json | jq -r 'to_entries[] | select(.key == "nameservers") | .value.value[]'
